/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4d44e3",
        primary: "#3525cd",
        "secondary-container": "#d0e1fb",
        "surface-dim": "#dcd8e5",
        "surface-container-highest": "#e4e1ee",
        "inverse-on-surface": "#f3effc",
        "surface-container-low": "#f5f2ff",
        "on-primary-container": "#dad7ff",
        background: "#fcf8ff",
        "on-background": "#1b1b24",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        tertiary: "#7e3000",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e1ee",
        "inverse-surface": "#302f39",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae6f4",
        outline: "#777587",
        "on-secondary-container": "#54647a",
        error: "#ba1a1a",
        "surface-bright": "#fcf8ff",
        "secondary-fixed": "#d3e4fe",
        "on-primary-fixed": "#0f0069",
        secondary: "#505f76",
        "surface-container": "#f0ecf9",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "tertiary-container": "#a44100",
        "on-surface": "#1b1b24",
        "on-surface-variant": "#464555",
        surface: "#fcf8ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-container": "#ffd2be",
        "outline-variant": "#c7c4d8",
        "primary-fixed": "#e2dfff",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        card: "0px 4px 12px rgba(0, 0, 0, 0.05)",
        "card-hover": "0px 8px 20px rgba(0, 0, 0, 0.08)",
        modal: "0px 10px 25px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
